name: Trying to work
description: A collection of free spaces to work online around Belfast City Centre
author: Michael
author_link: http://michaelmckeever.co
markdown: redcarpet
highlighter: rouge # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

collections:
- spaces
